version: "3.9"

name: zeroDay-kit
services:
  postgres:
    image: postgres:18.1
    container_name: zeroDay-kit-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: zeroDay-kit
    ports:
      - "5432:5432"